services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=odoo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U odoo" ]
      interval: 5s
      timeout: 5s
      retries: 5

  odoo:
    image: keyboardslayer/odoo-vuln-werkzeug
    ports:
      - "8069:8069"
    depends_on:
      postgres:
        condition: service_healthy

    entrypoint: /opt/odoo/odoo-bin --db_host=postgres --db_user=odoo --db_password=odoo -i base -d odoo-vuln
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
